### PR TITLE
US15 Alex

### PR DESCRIPTION
**Pull request by Oleksandrozhoh**
Finished US15_searchFunctionality ; added 2 utility methods: sleep() and verifyTitleContains() ;

### CODE REVIEW

**Review by daurentk — COMMENTED** [review]
Was your code run successful?
Some locators in the MainPage seems do not work for me.

**Comment by Oleksandrozhoh** [comment]
Which locators you mean specifically?

**Comment by daurentk** [comment]
> Which locators you mean specifically?

>I tried "//ul//li/div/a/div[2]" and "//span[.='wooden spoon stand']/.." but probably incorrect way. 
If it works OK on your side- no problem. I'm fine with merging as long as Soukaina is OK.

**Comment by soukainaelmir** [comment]
I run the code multiple time, sometimes it fails and then it passes I think the website it's not stable I had the same problem. 
but the code is fine I approve merging to master.

**Review by soukainaelmir — APPROVED** [review]
approve

**Review by daurentk — APPROVED** [review]
Merged now.

**Pull request merged**
